### ISSUE TITLE
[Feat] home 화면 구현을 통한 모듈 의존성 연결

### ISSUE THREAD

**Issue by uuranus** [PEPLGreenmate/greenmate_tech_android#9]
# Description
화면 구성을 해보면서 모듈의 의존성을 연결

# TODO
- [ ] model 데이터 클래스 생성
- [ ] home 화면 간단 구현 with compose
- [ ] repository를 통해 ui와 model 연결

# ETC
